name: Verify and Publish

on:
  push:
  workflow_dispatch:

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run lint-typecheck
      - name: ESLint
        run: npm run lint-eslint
      - name: Prettier
        run: npm run lint-prettier
      - name: depcheck
        run: npm run lint-depcheck

  build:
    name: Build
    runs-on: ubuntu-latest
    environment: github-pages
    needs: verify

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --base=/${{ github.event.repository.name }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: github-pages
    needs: build

    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'

    concurrency:
      group: github-pages
      cancel-in-progress: false
    permissions:
      id-token: write
      pages: write
      contents: write
      packages: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
